name: Provision OpenShift Lab

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Name of your cluster (e.g., dev-lab-1)'
        required: true
        type: string
      worker_count:
        description: 'Number of Worker Nodes'
        required: true
        default: '2'
        type: choice
        options:
          - '1'
          - '2'
      acknowledgment:
        description: 'NOTE: This cluster will be automatically deleted in 72 hours. Please reach out to Shrey Raut via Slack if you need it running longer. Acknowledge the same to continue the build.'
        required: true
        type: boolean
        default: false

jobs:
  build-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Acknowledgment
        run: |
          if [ "${{ inputs.acknowledgment }}" != "true" ]; then
            echo "Error: You must acknowledge the 72-hour deletion policy."
            exit 1
          fi

      - name: Download OpenShift Installer
        run: |
          wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz
          tar xvf openshift-install-linux.tar.gz
          sudo mv openshift-install /usr/local/bin/

      - name: Generate install-config.yaml
        env:
          CLUSTER_NAME: ${{ inputs.cluster_name }}
          WORKER_COUNT: ${{ inputs.worker_count }}
          # Hardcoding machine type and gcp region values
          WORKER_MACHINE_TYPE: 'e2-standard-4'
          GCP_REGION: 'us-central1'
          BASE_DOMAIN: ${{ secrets.GCP_BASE_DOMAIN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          PULL_SECRET: ${{ secrets.RH_PULL_SECRET }}
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
        run: |
          mkdir workspace
          envsubst < install-config-templaye.yaml > workspace/install-config.yaml
          
      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_SA_CREDENTIALS }}" > /tmp/gcp.json

          # In GitHub Actions, if you just run export VAR=VALUE in one step, the next step in your pipeline will forget it completely. 
          # You have to write variables to a special system file called $GITHUB_ENV to make them stick around for the whole job.

          # GOOGLE_APPLICATION_CREDENTIALS for gsutil, GOOGLE_CREDENTIALS for openshift-install
          # >> appends a new line to the file without overwriting the file, > overwrites the file
          
          echo "GOOGLE_CREDENTIALS=/tmp/gcp.json" >> $GITHUB_ENV 
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp.json" >> $GITHUB_ENV 
        

      - name: Run OpenShift Installer
        run: |
          openshift-install create cluster --dir=workspace --log-level=info

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload Cluster Metadata to GCS
        if: always() 
        run: |
          gsutil cp workspace/metadata.json gs://${{ secrets.GCP_STATE_BUCKET }}/${{ inputs.cluster_name }}/metadata.json

      - name: Output Login Credentials
        if: success() 
        run: |
          echo "======================================================"
          echo "CLUSTER DEPLOYMENT COMPLETE"
          echo "======================================================"
          echo "Web Console URL: $(cat workspace/auth/console-url)"
          echo "Username: kubeadmin"
          echo "Password: $(cat workspace/auth/kubeadmin-password)"
          echo "------------------------------------------------------"
          echo "To use the CLI, log into the Web Console, click your"
          echo "username in the top right, and select 'Copy login command'."
          echo "======================================================"